nimzero_stripe:

    # Used to configure the Stripe version used by the StripeClient, if null use your Stripe account default version
    api_version: ~

    # The tolerance is the allowed difference in seconds between the current timestamp and the timestamp in the request header
    tolerance: 300

    modes:

        # Stripe Live mode
        live:

            # Is Live mode enabled
            enabled: true

            # Consider storing the following secrets using symfony secrets

            # Your API keys
            public_key: '%env(STRIPE_LIVE_API_PUBLIC_KEY)%'
            secret_key: '%env(STRIPE_LIVE_API_SECRET_KEY)%'

            # Your webhook signing secret
            webhook_secret: '%env(STRIPE_LIVE_WEBHOOK_SECRET)%'

        # Stripe Test mode
        test:

            # Is Test mode enabled
            enabled: true

            # Consider storing the following secrets using symfony secrets

            # Your API keys
            public_key: '%env(STRIPE_TEST_API_PUBLIC_KEY)%'
            secret_key: '%env(STRIPE_TEST_API_SECRET_KEY)%'

            # Your webhook signing secret
            webhook_secret: '%env(STRIPE_TEST_WEBHOOK_SECRET)%'