services:
  _defaults:
      autowire: true
      autoconfigure: true

  Nimzero\StripeBundle\:
    resource: '../src/'
    exclude: '../src/{DependencyInjection,Entity}'

  nimzero.stripe_bundle.service.stripe:
    public: false
    class: Nimzero\StripeBundle\Service\StripeService
    arguments:
      $stripe_config: ''

  nimzero.stripe_bundle.maker.listener:
    public: false
    class: Nimzero\StripeBundle\Maker\MakeListener
    arguments:
      - '@maker.file_manager'

  nimzero.stripe_bundle.maker.subscriber:
    public: false
    class: Nimzero\StripeBundle\Maker\MakeSubscriber

  Nimzero\StripeBundle\Service\StripeServiceInterface: '@nimzero.stripe_bundle.service.stripe'
  Nimzero\StripeBundle\Maker\MakeListener: '@nimzero.stripe_bundle.maker.listener'
  Nimzero\StripeBundle\Maker\MakeSubscriber: '@nimzero.stripe_bundle.maker.subscriber'
