services:
  _defaults:
      autowire: true
      autoconfigure: true

  Nimzero\StripeBundle\:
    resource: '../src/'
    exclude: '../src/{DependencyInjection,Entity}'

  nimzero.stripe_bundle.service.stripe:
    public: false
    class: Nimzero\StripeBundle\Service\StripeService
    arguments:
      $api_secret_key: ''

  nimzero.stripe_bundle.maker.listener:
    public: false
    class: Nimzero\StripeBundle\Maker\MakeListener
    arguments:
      - '@maker.file_manager'

  Nimzero\StripeBundle\Service\StripeInterface: '@nimzero.stripe_bundle.service.stripe'
  Nimzero\StripeBundle\Maker\MakeListener: '@nimzero.stripe_bundle.maker.listener'
