services:
  # default configuration for services in *this* file
  _defaults:
      autowire: true      # Automatically injects dependencies in your services.
      autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  Nimzero\StripeBundle\:
    resource: '../src/'
    exclude: '../src/{DependencyInjection,Entity}'

  nimzero.stripe_bundle.service.stripe:
    public: false
    class: Nimzero\StripeBundle\Service\StripeService
    arguments:
      $api_secret_key: ''

  nimzero.stripe_bundle.maker.listener:
    public: false
    class: Nimzero\StripeBundle\Maker\MakeListener
    arguments:
      - '@maker.file_manager'

  Nimzero\StripeBundle\Service\StripeInterface: '@nimzero.stripe_bundle.service.stripe'
  Nimzero\StripeBundle\Maker\MakeListener: '@nimzero.stripe_bundle.maker.listener'
