services:
    _defaults:
        autowire: true
        autoconfigure: true
    
    Nimzero\StripeBundle\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'

    nimzero_stripe_bundle.stripe_helper:
        class: Nimzero\StripeBundle\Service\StripeHelper
        arguments:
            '$stripe_config': null

    nimzero_stripe_bundle.maker.webhook_from_events:
        class: Nimzero\StripeBundle\Maker\MakeWebhookFromEvents
        arguments:
            '$eventRegistry': '@maker.event_registry'
    
    nimzero_stripe_bundle.twig_extension_runtime:
        class: Nimzero\StripeBundle\Twig\StripeTwigRuntime
        arguments:
            '$stripeHelper': '@nimzero_stripe_bundle.stripe_helper'

    Nimzero\StripeBundle\Service\StripeHelper: '@nimzero_stripe_bundle.stripe_helper'
